"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:10:16.100225
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proc_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('requisition_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('order_date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proc_orders_order_no'), 'proc_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_proc_orders_requisition_id'), 'proc_orders', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_proc_orders_status'), 'proc_orders', ['status'], unique=False)
    op.create_index(op.f('ix_proc_orders_supplier_id'), 'proc_orders', ['supplier_id'], unique=False)
    op.create_table('proc_requisitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('req_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('expected_date', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proc_requisitions_req_no'), 'proc_requisitions', ['req_no'], unique=True)
    op.create_index(op.f('ix_proc_requisitions_status'), 'proc_requisitions', ['status'], unique=False)
    op.create_index(op.f('ix_proc_requisitions_title'), 'proc_requisitions', ['title'], unique=False)
    op.create_table('proc_suppliers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proc_suppliers_code'), 'proc_suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_proc_suppliers_level'), 'proc_suppliers', ['level'], unique=False)
    op.create_index(op.f('ix_proc_suppliers_name'), 'proc_suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_proc_suppliers_status'), 'proc_suppliers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proc_suppliers_status'), table_name='proc_suppliers')
    op.drop_index(op.f('ix_proc_suppliers_name'), table_name='proc_suppliers')
    op.drop_index(op.f('ix_proc_suppliers_level'), table_name='proc_suppliers')
    op.drop_index(op.f('ix_proc_suppliers_code'), table_name='proc_suppliers')
    op.drop_table('proc_suppliers')
    op.drop_index(op.f('ix_proc_requisitions_title'), table_name='proc_requisitions')
    op.drop_index(op.f('ix_proc_requisitions_status'), table_name='proc_requisitions')
    op.drop_index(op.f('ix_proc_requisitions_req_no'), table_name='proc_requisitions')
    op.drop_table('proc_requisitions')
    op.drop_index(op.f('ix_proc_orders_supplier_id'), table_name='proc_orders')
    op.drop_index(op.f('ix_proc_orders_status'), table_name='proc_orders')
    op.drop_index(op.f('ix_proc_orders_requisition_id'), table_name='proc_orders')
    op.drop_index(op.f('ix_proc_orders_order_no'), table_name='proc_orders')
    op.drop_table('proc_orders')
    # ### end Alembic commands ###
